sudo: required
services:
  - docker

before_install:
  - docker build -t amoljagadambe/fibonacci-calculator -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amoljagadambe/fibonacci-calculator npm run test

after_success:
  - docker build -t amoljagadambe/multi-client ./client
  - docker build -t amoljagadambe/multi-nginx ./nginx
  - docker build -t amoljagadambe/multi-server ./server
  - docker build -t amoljagadambe/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to  docker hun
  - docker push amoljagadambe/multi-client
  - docker push amoljagadambe/multi-nginx
  - docker push amoljagadambe/multi-server
  - docker push amoljagadambe/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "ap-south-1"
#  app: "fibonacci-calculator"
#  env: "Fibonaccicalculator-env"
#  bucket_name: "elasticbeanstalk-ap-south-1-499977662464"
#  bucket_path: "fibonacci-calculator"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY